version: "3.7"
services:
  cardinal_api:
    image: gyroskan/cardinal_api:latest
    container_name: cardinal_api
    restart: unless-stopped
    environment:
      - SECRET=test-secret_used#for!token/sign
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PWD=root
      - DB_NAME=cardinal
    depends_on:
      - "db"
    ports:
      - "5005:5005"
    networks:
      - cardinal
      - db
  db:
    container_name: cardinal_api_db
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: cardinal
    volumes:
      - ./data:/var/liv/mysql
    networks:
      - db

networks:
  db:
  cardinal:
    external: true
