// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2022-04-18 08:30:02.330698554 +0200 CEST m=+9.123488264
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "gyroskan@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/guilds": {
            "get": {
                "description": "Fetch all guilds.",
                "tags": [
                    "Guilds"
                ],
                "summary": "Get Guilds",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            }
        },
        "/guilds/": {
            "post": {
                "description": "Create a new Guild",
                "tags": [
                    "Guilds"
                ],
                "summary": "Create guild",
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            }
        },
        "/guilds/{guildID}": {
            "get": {
                "description": "Fetch a specific guild",
                "tags": [
                    "Guilds"
                ],
                "summary": "Get guild",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "fetch members",
                        "name": "members",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a guild",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Guilds"
                ],
                "summary": "Delete guild",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "206": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            },
            "patch": {
                "description": "Update fields of a guild",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Guilds"
                ],
                "summary": "Update guild values",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Guild modifications",
                        "name": "guild",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Guild"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/channels": {
            "get": {
                "description": "Fetch all channels of the guild.",
                "tags": [
                    "Channels"
                ],
                "summary": "Get Guild channels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "ignored channels only",
                        "name": "ignored",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "xpBlacklist channels only",
                        "name": "xpBlacklist",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "post": {
                "description": "Create a new channel for a guild.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Create channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Channel values",
                        "name": "channel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Channel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created channel",
                        "schema": {
                            "$ref": "#/definitions/models.Channel"
                        }
                    },
                    "400": {
                        "description": "Wrong values"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/channels/{channelID}": {
            "get": {
                "description": "Fetch the channel of the guild.",
                "tags": [
                    "Channels"
                ],
                "summary": "Get one Guild Channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "channel id",
                        "name": "channelID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a guild channel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Delete guild channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Channel id",
                        "name": "channelID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "206": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            },
            "patch": {
                "description": "Update fields of a guild's channel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "Update channel values",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Channel id",
                        "name": "channelID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members": {
            "get": {
                "description": "Fetch all members of the guild.",
                "tags": [
                    "Members"
                ],
                "summary": "Get Guild Members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "limit to fetch",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "0",
                        "description": "higher last id fetched",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "post": {
                "description": "Create a new member from a guild.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Members"
                ],
                "summary": "Create member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Member values",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created member",
                        "schema": {
                            "$ref": "#/definitions/models.Member"
                        }
                    },
                    "400": {
                        "description": "Wrong values"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/reset": {
            "post": {
                "description": "Reset level and xp for all guild's members.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Members"
                ],
                "summary": "Reset guild's members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Member reset"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/{memberID}": {
            "get": {
                "description": "Fetch the member of the guild.",
                "tags": [
                    "Members"
                ],
                "summary": "Get one Guild Member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a guild member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Members"
                ],
                "summary": "Delete guild member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "206": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            },
            "patch": {
                "description": "Update fields of a guild's member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Members"
                ],
                "summary": "Update member value",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/{memberID}/bans": {
            "get": {
                "description": "Fetch all bans of the member.",
                "tags": [
                    "Bans"
                ],
                "summary": "Get Member Bans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "post": {
                "description": "Create a new ban for a member.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bans"
                ],
                "summary": "Create ban",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created role",
                        "schema": {
                            "$ref": "#/definitions/models.Ban"
                        }
                    },
                    "400": {
                        "description": "Wrong values"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/{memberID}/bans/{banID}": {
            "get": {
                "description": "Fetch the ban of the member.",
                "tags": [
                    "Bans"
                ],
                "summary": "Get one ban",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ban id",
                        "name": "banID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a member's ban",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bans"
                ],
                "summary": "Delete member's ban",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ban id",
                        "name": "banID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "206": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/{memberID}/reset": {
            "post": {
                "description": "Reset level and xp for the specific guild's members.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Members"
                ],
                "summary": "Reset member from a guild",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Member reset"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/{memberID}/warns": {
            "get": {
                "description": "Fetch all warns of the member.",
                "tags": [
                    "Warns"
                ],
                "summary": "Get Member Warns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "post": {
                "description": "Create a new warn for a member.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warns"
                ],
                "summary": "Create warn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created warn",
                        "schema": {
                            "$ref": "#/definitions/models.Warn"
                        }
                    },
                    "400": {
                        "description": "Wrong values"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/members/{memberID}/warns/{warnID}": {
            "get": {
                "description": "Fetch the warn of the member.",
                "tags": [
                    "Warns"
                ],
                "summary": "Get one warn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "warn id",
                        "name": "warnID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a member's warn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warns"
                ],
                "summary": "Delete member's warn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member id",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "warn id",
                        "name": "warnID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "206": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/reset": {
            "post": {
                "description": "Reset guild parameters to default values. Do not change members values.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Guilds"
                ],
                "summary": "Reset guild",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/roles": {
            "get": {
                "description": "Fetch all roles of the guild.",
                "tags": [
                    "Roles"
                ],
                "summary": "Get Guild roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "reward from this lvl only",
                        "name": "reward",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "ignored roles only",
                        "name": "ignored",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "xpBlacklist roles only",
                        "name": "xpBlacklist",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "post": {
                "description": "Create a new role for a guild.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Create role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role values",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created role",
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    },
                    "400": {
                        "description": "Wrong values"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/guilds/{guildID}/roles/{roleID}": {
            "get": {
                "description": "Fetch the role of the guild.",
                "tags": [
                    "Roles"
                ],
                "summary": "Get one Guild role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a guild role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Delete guild role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "206": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            },
            "patch": {
                "description": "Update fields of a guild's role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Update role values",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guild id",
                        "name": "guildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role id",
                        "name": "roleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Fountd"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/users/": {
            "get": {
                "description": "Get a list of existing users",
                "tags": [
                    "Users"
                ],
                "summary": "Get Users",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Login to get user token",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "login invalid"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "description": "Get the logged in user",
                "tags": [
                    "Users"
                ],
                "summary": "Get Logged in User",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "User values",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserCreation"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Wrong values"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/users/{username}": {
            "get": {
                "description": "Get a specific user",
                "tags": [
                    "Users"
                ],
                "summary": "Get User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "post": {
                "description": "Update User access level",
                "tags": [
                    "Users"
                ],
                "summary": "Update User access level",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "access_level",
                        "name": "access_level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "NotFound"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Delete definitively the user.",
                "tags": [
                    "Users"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "NotFound"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "patch": {
                "description": "Update specified User fields",
                "tags": [
                    "Users"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "fields to modify",
                        "name": "userModif",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserModification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid values"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "NotFound"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            }
        },
        "/users/{username}/ban": {
            "post": {
                "description": "Update User ban. POST to unbann, DELETE to ban.",
                "tags": [
                    "Users"
                ],
                "summary": "Ban User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "NotFound"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            },
            "delete": {
                "description": "Update User ban. POST to unbann, DELETE to ban.",
                "tags": [
                    "Users"
                ],
                "summary": "Ban User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "NotFound"
                    },
                    "500": {
                        "description": "Server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Ban": {
            "type": "object",
            "properties": {
                "autoBan": {
                    "type": "boolean"
                },
                "banID": {
                    "type": "integer"
                },
                "banReason": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "bannedAt": {
                    "type": "string"
                },
                "bannerID": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "guildID": {
                    "type": "string"
                },
                "memberID": {
                    "type": "string"
                }
            }
        },
        "models.Channel": {
            "type": "object",
            "properties": {
                "channelID": {
                    "type": "string"
                },
                "guildID": {
                    "type": "string"
                },
                "ignored": {
                    "type": "boolean"
                },
                "wpBlacklisted": {
                    "type": "boolean"
                }
            }
        },
        "models.Guild": {
            "type": "object",
            "properties": {
                "allowModeration": {
                    "type": "boolean"
                },
                "banTime": {
                    "type": "integer"
                },
                "disabledCommands": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "guildID": {
                    "type": "string"
                },
                "guildName": {
                    "type": "string"
                },
                "lvlChannel": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "lvlReplace": {
                    "type": "boolean"
                },
                "lvlResponse": {
                    "type": "integer"
                },
                "maxWarns": {
                    "type": "integer"
                },
                "prefix": {
                    "type": "string"
                },
                "privateWelcomeMsg": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "reportChannel": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "welcomeChannel": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "welcomeMsg": {
                    "$ref": "#/definitions/nulltype.NullString"
                }
            }
        },
        "models.Member": {
            "type": "object",
            "properties": {
                "guildID": {
                    "type": "string"
                },
                "joinedAt": {
                    "$ref": "#/definitions/nulltype.NullTime"
                },
                "left": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "memberID": {
                    "type": "string"
                },
                "xp": {
                    "type": "integer"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "guildID": {
                    "type": "string"
                },
                "ignored": {
                    "type": "boolean"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "reward": {
                    "type": "integer"
                },
                "roleID": {
                    "type": "string"
                },
                "xpBlacklisted": {
                    "type": "boolean"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "accessLvl": {
                    "type": "integer"
                },
                "banned": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "discordID": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserCreation": {
            "type": "object",
            "properties": {
                "discordID": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserModification": {
            "type": "object",
            "properties": {
                "discordID": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "email": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Warn": {
            "type": "object",
            "properties": {
                "guildID": {
                    "type": "string"
                },
                "memberID": {
                    "type": "string"
                },
                "warnID": {
                    "type": "integer"
                },
                "warnReason": {
                    "$ref": "#/definitions/nulltype.NullString"
                },
                "warnedAt": {
                    "type": "string"
                },
                "warnerID": {
                    "$ref": "#/definitions/nulltype.NullString"
                }
            }
        },
        "nulltype.NullString": {
            "type": "object"
        },
        "nulltype.NullTime": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "cardinal.gyroskan.com",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Cardinal API",
	Description:      "The API to interact with cardinal discord bot database.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
